# Database config
spring.datasource.url=jdbc:mysql://localhost:3306/loan_management_db
spring.datasource.username=root
spring.datasource.password=Ashu@121718

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


